micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: ${JDBC_URL:jdbc:mysql://10.11.12.28:3306/mn_playground}
    username: ${JDBC_USERNAME:root}
    password: ${JDBC_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true