micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://localhost:3306/my_playground
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true