micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://mysql:3306/testdb
    username: testuser
    password: testpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true