micronaut:
  application:
    name: micronaut-crud

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mn_playground}?useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Airjorda7}
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  datasources:
    default:
      enabled: true
