name: Build and Test with MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root --password=root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant permission to execute gradlew
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew clean build
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: testdb
