name: CI Pipeline

on:
  push:
    branches:
      - jdbc
  pull_request:
    branches:
      - jdbc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker compose
        run: sudo apt-get install docker-compose

      - name: Docker compose up
        run: docker-compose up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build and test
        run: ./gradlew clean build

      - name: Stop and remove services
        if: always()
        run: docker-compose down