name: Build and Merge

on:
  pull_request:
    branches:
      - jdbc
      - main
  push:
    branches:
      - main
      - jdbc

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -ppassword" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.10"

      - name: Build with Gradle 8.10
        run: gradle build

      - name: Build JAR
        run: ./gradlew build 

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: build/libs/*.jar 